### ISSUE TITLE
Thank your for update but... Cheat still doesn't work.

### ISSUE THREAD

**Issue by 0c110** [ioncodes/ESP-It#11]
The game doesn't crash anymore, but after the injection I get a blank console window with nothing written in it. There is also no text at the top of the game like before, and the witch nicknames are not visible. I'm using the Epic Games version of the game if that matters.

**Comment by Forza119** [comment]
Hit **INSERT**. It is explained in the README.

Its disabled by default, the ESP turns on with insert.
This was the **intended behavior before the update**, but it didn't do that due to reasons, so the ESP was always-on.

You can confirm it injected and loaded by hitting F2 to bring up the in-game console. or Hit INSERT and the words "i have a small pp" will appear in the top left.

**Comment by 0c110** [comment]
> Hit **INSERT**. It is explained in the README.
> 
> Its disabled by default, the ESP turns on with insert. This was the **intended behavior before the update**, but it didn't do that due to reasons, so the ESP was always-on.
> 
> You can confirm it injected and loaded by hitting F2 to bring up the in-game console. or Hit INSERT and the words "i have a small pp" will appear in the top left.

oh ok, thank you, i will try

**Comment by 0c110** [comment]
> Hit **INSERT**. It is explained in the README.
> 
> Its disabled by default, the ESP turns on with insert. This was the **intended behavior before the update**, but it didn't do that due to reasons, so the ESP was always-on.
> 
> You can confirm it injected and loaded by hitting F2 to bring up the in-game console. or Hit INSERT and the words "i have a small pp" will appear in the top left.

yep, it working, thank you again
